package main

import (
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"

	"github.com/TheSlopMachine/llm-router/scripts/shared"
)

const sdkModule = "github.com/TheSlopMachine/llm-router-sdk"

func main() {
	remote := flag.String("remote", "https", "clone protocol: https|ssh")
	flag.Parse()
	if *remote != "https" && *remote != "ssh" {
		shared.Failf("invalid --remote %q: must be https or ssh", *remote)
	}

	root, err := shared.RootDir()
	if err != nil {
		shared.Failf("%v", err)
	}
	adaptersConf := filepath.Join(root, "adapters.conf")
	workspaceDir := filepath.Join(root, ".workspace")

	if _, err := os.Stat(adaptersConf); os.IsNotExist(err) {
		shared.Stepf("Creating %s...", adaptersConf)
		header := "# External adapter registry\n# Format: <module-path>\n"
		if _, err := shared.WriteIfChanged(adaptersConf, []byte(header), 0644); err != nil {
			shared.Failf("%v", err)
		}
	}

	if err := os.MkdirAll(workspaceDir, 0755); err != nil {
		shared.Failf("create .workspace: %v", err)
	}

	sdkDir := filepath.Join(workspaceDir, filepath.Base(sdkModule))
	ensureClone(sdkModule, sdkDir, *remote)

	mods := readModules(adaptersConf)
	for _, mod := range mods {
		if mod == sdkModule {
			shared.Stepf("Skip %s (already as SDK)", mod)
			continue
		}
		dir := filepath.Join(workspaceDir, filepath.Base(mod))
		ensureClone(mod, dir, *remote)
	}

	writeGoWork(root, workspaceDir)
	writeAdaptersGo(root, mods)
	syncWork(root)
	shared.OKf("Workspace ready (.workspace + go.work + adapters.go)")
}

func readModules(path string) []string {
	raw, err := os.ReadFile(path)
	if err != nil {
		shared.Failf("read adapters.conf: %v", err)
	}
	var mods []string
	for _, line := range strings.Split(string(raw), "\n") {
		line = strings.TrimSpace(strings.TrimSuffix(line, "\r"))
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		fields := strings.Fields(line)
		if len(fields) == 0 {
			continue
		}
		mods = append(mods, fields[0])
	}
	return mods
}

func cloneURL(mod, remote string) string {
	if remote == "ssh" {
		parts := strings.SplitN(mod, "/", 2)
		if len(parts) != 2 {
			shared.Failf("invalid module path %q", mod)
		}
		return "git@" + parts[0] + ":" + parts[1] + ".git"
	}
	return "https://" + mod + ".git"
}

func ensureClone(mod, dir, remote string) {
	url := cloneURL(mod, remote)
	if st, err := os.Stat(dir); err == nil && st.IsDir() {
		if _, err := os.Stat(filepath.Join(dir, ".git")); os.IsNotExist(err) {
			fmt.Printf("[!] Local dir %s exists without .git — skip clone (local dev)\n", dir)
			return
		}
		cur, err := gitOut(dir, "remote", "get-url", "origin")
		if err != nil || strings.TrimSpace(cur) == "" {
			shared.Stepf("Exists %s (no remote), skip", dir)
			return
		}
		if strings.TrimSpace(cur) != url {
			shared.Stepf("Updating remote %s: %s -> %s", dir, strings.TrimSpace(cur), url)
			if err := gitRun(dir, "remote", "set-url", "origin", url); err != nil {
				shared.Failf("git remote set-url in %s: %v", dir, err)
			}
			return
		}
		shared.Stepf("Exists %s, skip", dir)
		return
	}
	shared.Stepf("Cloning %s (%s) -> %s", mod, remote, dir)
	if err := gitRun("", "clone", url, dir); err != nil {
		shared.Failf("git clone %s: %v", mod, err)
	}
}

func gitRun(dir string, args ...string) error {
	cmd := exec.Command("git", args...)
	if dir != "" {
		cmd.Dir = dir
	}
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

func gitOut(dir string, args ...string) (string, error) {
	cmd := exec.Command("git", args...)
	cmd.Dir = dir
	out, err := cmd.Output()
	return string(out), err
}

func writeGoWork(root, workspaceDir string) {
	entries, err := os.ReadDir(workspaceDir)
	if err != nil {
		shared.Failf("read .workspace: %v", err)
	}
	var uses []string
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		if _, err := os.Stat(filepath.Join(workspaceDir, e.Name(), "go.mod")); err != nil {
			continue
		}
		uses = append(uses, e.Name())
	}
	sort.Strings(uses)
	var b strings.Builder
	b.WriteString("go 1.25.0\n\nuse (\n  .\n")
	for _, u := range uses {
		fmt.Fprintf(&b, "  ./.workspace/%s\n", u)
	}
	b.WriteString(")\n")
	wrote, err := shared.WriteIfChanged(filepath.Join(root, "go.work"), []byte(b.String()), 0644)
	if err != nil {
		shared.Failf("%v", err)
	}
	if wrote {
		shared.Stepf("Generated go.work")
	}
}

func writeAdaptersGo(root string, mods []string) {
	var b strings.Builder
	b.WriteString("// Code generated by scripts/workspace. DO NOT EDIT.\n\npackage main\n\n")
	var imports []string
	for _, mod := range mods {
		if mod == sdkModule {
			continue
		}
		imports = append(imports, mod)
	}
	sort.Strings(imports)
	if len(imports) > 0 {
		b.WriteString("import (\n")
		for _, mod := range imports {
			fmt.Fprintf(&b, "\t_ %q\n", mod)
		}
		b.WriteString(")\n")
	}
	wrote, err := shared.WriteIfChanged(filepath.Join(root, "adapters.go"), []byte(b.String()), 0644)
	if err != nil {
		shared.Failf("%v", err)
	}
	if wrote {
		shared.Stepf("Generated adapters.go")
	}
}

func syncWork(root string) {
	cmd := exec.Command("go", "work", "sync")
	cmd.Dir = root
	cmd.Env = shared.EnvWithoutGowork()
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		shared.Failf("go work sync: %v", err)
	}
}
