# =============================================================================
# Makefile  -  cross-platform replacement for proj.cmd
# Requires: go, swag, npm, zip, git
#           sha256sum (Linux / Git Bash) or shasum (macOS)
# Works on: Linux, macOS, Windows (via make.ps1 / make.cmd, Git Bash, MSYS2, WSL)
# =============================================================================

# -- Shell ---------------------------------------------------------------------
# On Windows use make.ps1 which prepends Git's usr/bin to PATH so bash and
# coreutils (printf, mkdir ...) are visible to CreateProcess.
# NOTE: $(shell ...) at parse time still bypasses SHELL on Windows32 Make, so
# the OS blocks below only call native executables (go, git, powershell).
SHELL      := bash
.SHELLFLAGS := -c

VERSION    ?= dev
BINARY     := llm-router
UI_DIR     := web
DOCS_OUT   := build/docs
PUBLISH    := build/release
ADAPTERS   := adapters.conf
PLUGINS    := plugins/plugins.go

# -- OS-specific settings ------------------------------------------------------
ifeq ($(OS),Windows_NT)
  # --- Windows: parse-time calls use only native Windows executables ----------
  LOCAL_BIN  := $(BINARY).exe
  NPM        := npm.cmd
  # go.exe is a native Windows binary - CreateProcess can invoke it directly.
  # $(subst) converts backslashes (C:\Users\...) to forward slashes so the
  # resulting path is usable inside Git Bash recipes.
  GOPATH     := $(subst \,/,$(shell go env GOPATH))
  SWAG       := $(GOPATH)/bin/swag.exe
  # git.exe is also natively callable.  If the repo check fails the var is empty.
  _GIT_RAW   := $(shell git rev-parse --short HEAD)
  GIT_COMMIT := $(if $(_GIT_RAW),$(_GIT_RAW),unknown)
  # powershell.exe is natively callable.  'Z' is not a .NET format specifier
  # so it is emitted as a literal character in the output.
  BUILD_TIME := $(shell powershell -NoProfile -Command \
    "[System.DateTime]::UtcNow.ToString('yyyy-MM-ddTHH:mm:ssZ')")
  # sha256sum ships with Git for Windows coreutils; used in bash recipes below.
  SHA256     := sha256sum
else
  # --- Unix (Linux / macOS / MSYS2 / WSL) ------------------------------------
  SHELL      := bash
  NPM        := npm
  UNAME_S    := $(shell uname -s)
  ifneq ($(filter MINGW% CYGWIN%,$(UNAME_S)),)
    LOCAL_BIN := $(BINARY).exe
  else
    LOCAL_BIN := $(BINARY)
  endif
  GOPATH     := $(shell go env GOPATH 2>/dev/null)
  SWAG       := $(GOPATH)/bin/swag
  GIT_COMMIT := $(shell git rev-parse --short HEAD 2>/dev/null || echo unknown)
  BUILD_TIME := $(shell date -u '+%Y-%m-%dT%H:%M:%SZ')
  SHA256     := $(shell command -v sha256sum 2>/dev/null || echo "shasum -a 256")
endif

LDFLAGS     = -s -w \
              -X main.Version=$(VERSION) \
              -X main.GitCommit=$(GIT_COMMIT) \
              -X main.BuildTime=$(BUILD_TIME)

# -- Release target platforms --------------------------------------------------
PLATFORMS := \
  windows/amd64 windows/386   windows/arm64 \
  linux/amd64   linux/386     linux/arm64   linux/arm \
  darwin/amd64  darwin/arm64 \
  freebsd/amd64 freebsd/386   freebsd/arm64

PLATFORM_TARGETS := $(addprefix _build_,$(subst /,_,$(PLATFORMS)))

.PHONY: help run build release clean prepare-frontend generate-plugins FORCE

# -- Default target ------------------------------------------------------------
help:
	@printf '\nUsage: make <target>\n\n'
	@printf 'Targets:\n'
	@printf '  run      Build frontend & docs, then run the server\n'
	@printf '  build    Build frontend & docs, compile for current platform\n'
	@printf '  release  Build frontend once, compile all platforms in parallel\n'
	@printf '  clean    Remove $(PUBLISH)/ and local binaries\n\n'
	@printf 'Variables:\n'
	@printf '  VERSION  Release version tag  (default: dev)\n\n'
	@printf 'Examples:\n'
	@printf '  make run\n'
	@printf '  make build\n'
	@printf '  VERSION=1.2.0 make release\n\n'

# -- generate-plugins ----------------------------------------------------------
generate-plugins:
	@printf '\n== Plugin Generation ==\n'
	@mkdir -p plugins
	@if [ ! -f "$(ADAPTERS)" ]; then \
		printf '# External adapter registry\n# Format: <module-path> @latest\n' > "$(ADAPTERS)"; \
	fi
	@printf '// Code generated by make generate-plugins. DO NOT EDIT.\n\npackage plugins\n\n' > "$(PLUGINS)"
	@if [ -s "$(ADAPTERS)" ] && grep -q '^[^#]' "$(ADAPTERS)" 2>/dev/null; then \
		printf 'import (\n' >> "$(PLUGINS)"; \
		grep -v '^#' "$(ADAPTERS)" | grep -v '^$$' | while read -r mod ver; do \
			printf '[>] Adding adapter: %s@%s\n' "$$mod" "$$ver"; \
			go get "$$mod@$$ver" || exit 1; \
			printf '\t_ "%s"\n' "$$mod" >> "$(PLUGINS)"; \
		done || exit 1; \
		printf ')\n' >> "$(PLUGINS)"; \
	fi
	@printf '[OK] Plugins generated.\n'

# -- prepare-frontend ----------------------------------------------------------
prepare-frontend: generate-plugins
	@printf '\n== Swagger Generation ==\n'
	@printf '[>] Generating Swagger docs...\n'
	"$(SWAG)" init --parseDependency --parseInternal --output "$(DOCS_OUT)"
	@printf '[OK] Swagger docs generated.\n'
	@printf '\n== Frontend ==\n'
	mkdir -p "$(UI_DIR)/src/lib/generated"
	cd "$(UI_DIR)" && $(NPM) install
	cd "$(UI_DIR)" && $(NPM) run build
	@printf '[OK] Frontend ready.\n'

# -- run -----------------------------------------------------------------------
run: prepare-frontend
	go run .

# -- build (current platform only) --------------------------------------------
build: prepare-frontend
	@printf '[>] Compiling for current platform...\n'
	go build -o "$(LOCAL_BIN)" .
	@printf '[OK] Binary: $(LOCAL_BIN)\n'

# -- Per-platform build (pattern rule) ----------------------------------------
#
# A single pattern rule replaces the old define/call/eval template.
# On GNU Make "Built for Windows32", $$ escaping in define-block recipes is
# broken: $$_goos is parsed as Make-variable $_ (empty) + literal "goos",
# not as a deferred shell variable.  A pattern rule avoids that entirely:
# $* is a proper Make automatic variable (the stem, e.g. "linux_amd64"),
# expanded by Make before the shell sees the recipe.  $(subst _,/,$*) turns
# the stem back into a GOOS/GOARCH pair without any space-as-replacement
# tricks.  All values are baked in as literals before the shell runs.

FORCE:

_build_%: FORCE
	@set -e; \
	_goos="$(patsubst %/,%,$(dir $(subst _,/,$*)))"; \
	_goarch="$(notdir $(subst _,/,$*))"; \
	if [ "$$_goos" = "windows" ]; then _bin="$(BINARY).exe"; else _bin="$(BINARY)"; fi; \
	mkdir -p "$(PUBLISH)/$${_goos}_$${_goarch}"; \
	printf '[>] Building %s/%s...\n' "$$_goos" "$$_goarch"; \
	GOOS=$$_goos GOARCH=$$_goarch go build -ldflags="$(LDFLAGS)" \
	    -o "$(PUBLISH)/$${_goos}_$${_goarch}/$$_bin" . \
	    || { printf '[FAIL] Build failed: %s/%s\n' "$$_goos" "$$_goarch"; exit 1; }; \
	(cd "$(PUBLISH)/$${_goos}_$${_goarch}" && zip -q "$(BINARY)_$${_goos}_$${_goarch}.zip" "$$_bin") \
	    || { printf '[FAIL] Archive failed: %s/%s\n' "$$_goos" "$$_goarch"; exit 1; }; \
	$(SHA256) "$(PUBLISH)/$${_goos}_$${_goarch}/$(BINARY)_$${_goos}_$${_goarch}.zip" \
	    > "$(PUBLISH)/_cksum_$${_goos}_$${_goarch}.tmp"; \
	printf '[OK] Done: %s/%s\n' "$$_goos" "$$_goarch"

# -- release -------------------------------------------------------------------
#
# 1. Prepares frontend once.
# 2. Spawns all platform builds in parallel via $(MAKE) -j.
#    make already tracks failures: any failing _build_* target causes make to
#    report an error and exit non-zero after parallel jobs finish, which is
#    equivalent to the original's fail-marker / counter approach.
# 3. Merges and sorts the isolated per-build checksum temp files into one
#    manifest, then removes the temp files.

release: prepare-frontend
	@printf '\n== Release - $(VERSION) ==\n'
	@printf '  Commit:     $(GIT_COMMIT)\n'
	@printf '  Build time: $(BUILD_TIME)\n\n'
	rm -rf "$(PUBLISH)"
	mkdir -p "$(PUBLISH)"
	@printf '[>] Building $(words $(PLATFORMS)) platforms in parallel...\n'
	$(MAKE) -j $(PLATFORM_TARGETS)
	@# Merge per-build checksum temp files into one sorted manifest
	@cat $(PUBLISH)/_cksum_*.tmp 2>/dev/null | sort > "$(PUBLISH)/checksums.txt"
	@rm -f $(PUBLISH)/_cksum_*.tmp
	@printf '\n[OK] Artifacts in  $(PUBLISH)/\n'
	@printf '[OK] Checksums in  $(PUBLISH)/checksums.txt\n'

# -- clean ---------------------------------------------------------------------
clean:
	@printf '[>] Cleaning ignored build artifacts...\n'
	git clean -fdX
	@printf '[OK] Clean.\n'
# -- Adapter management --------------------------------------------------------
.PHONY: add-adapter list-adapters remove-adapter

add-adapter:
	@if [ -z "$(MODULE)" ] || [ -z "$(VERSION)" ]; then \
		printf 'Usage: make add-adapter MODULE=github.com/user/adapter VERSION=v1.0.0\n'; \
		exit 1; \
	fi
	@printf '$(MODULE) $(VERSION)\n' >> "$(ADAPTERS)"
	@printf '[OK] Added $(MODULE)@$(VERSION) to $(ADAPTERS)\n'
	@printf '[>] Run "make build" to apply changes.\n'

list-adapters:
	@printf '\nConfigured adapters:\n'
	@if [ -f "$(ADAPTERS)" ]; then \
		grep -v '^#' "$(ADAPTERS)" | grep -v '^$$' || printf '  (none)\n'; \
	else \
		printf '  (none)\n'; \
	fi
	@printf '\n'

remove-adapter:
	@if [ -z "$(MODULE)" ]; then \
		printf 'Usage: make remove-adapter MODULE=github.com/user/adapter\n'; \
		exit 1; \
	fi
	@grep -v "^$(MODULE) " "$(ADAPTERS)" > "$(ADAPTERS).tmp" && mv "$(ADAPTERS).tmp" "$(ADAPTERS)"
	@printf '[OK] Removed $(MODULE) from $(ADAPTERS)\n'
	@printf '[>] Run "make build" to apply changes.\n'
